#!/bin/sh

# need edge for pandoc / docx support
cat >> /etc/apk/repositories << EOF
http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

apk update --no-cache

apk add --no-cache \
    make gcc ruby ruby-dev ruby-bundler graphviz ruby-nokogiri \
    unzip findutils which wget python2-dev zlib-dev \
    patch sudo bash libjpeg-turbo libjpeg-turbo-dev \
    asciidoctor pandoc

cat > Gemfile <<EOF
source 'https://rubygems.org'
gem 'asciidoctor'
gem 'asciidoctor-pdf'
# or specify the version explicitly
# gem 'asciidoctor', '1.5.6.1'
EOF

bundle

echo ""
echo "add pkg script completed"
echo ""

